"""initial

Revision ID: f0db8df2be54
Revises: 
Create Date: 2026-06-07 13:33:51.355575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0db8df2be54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hostels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pass_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'FACULTY', 'VISITOR', 'GUARD', 'SUPERVISOR', 'WARDEN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('blacklisted_rfids',
    sa.Column('rfid_tag_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('rfid_tag_id')
    )
    op.create_table('pass_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.Enum('UNDERGRAD', 'POSTGRAD', 'PHD', name='studenttier'), nullable=False),
    sa.Column('residency_status', sa.Enum('ON_CAMPUS', 'OFF_CAMPUS_COMMUTER', 'LONG_TERM_AWAY', name='residencystatus'), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('passes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('pass_type_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('has_exited', sa.Boolean(), nullable=False),
    sa.Column('has_entered', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('qr_secret_seed', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['pass_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pass_type_id'], ['pass_types.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pass_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('rfid_tag_id', sa.String(length=64), nullable=True),
    sa.Column('gate_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('denial_reason', sa.String(length=255), nullable=True),
    sa.Column('late_duration_seconds', sa.BigInteger(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pass_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pass_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pass_otps',
    sa.Column('pass_id', sa.Uuid(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pass_id')
    )
    op.create_table('pass_vehicles',
    sa.Column('pass_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('rfid_tag_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pass_id')
    )
    op.create_index(op.f('ix_pass_vehicles_rfid_tag_id'), 'pass_vehicles', ['rfid_tag_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pass_vehicles_rfid_tag_id'), table_name='pass_vehicles')
    op.drop_table('pass_vehicles')
    op.drop_table('pass_otps')
    op.drop_table('pass_approvals')
    op.drop_table('access_logs')
    op.drop_table('passes')
    op.drop_table('student_profiles')
    op.drop_table('pass_batches')
    op.drop_table('blacklisted_rfids')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('pass_types')
    op.drop_table('hostels')
    op.drop_table('gates')
    # ### end Alembic commands ###
